#Redis集群配置
# 使用lettuce连接池
spring:
  redis:
    timeout: 6000ms    # 连接超时时长（毫秒）
    database: 0
    cluster:
      nodes:
        - 192.168.10.120:7000
        - 192.168.10.120:7001
        - 192.168.10.111:7002
        - 192.168.10.111:7003
        - 192.168.10.114:7004
        - 192.168.10.114:7005
      max-redirects: 3 # 获取失败 最大重定向次数
    lettuce:  # 如果使用的 jedis 则将 lettuce 改成jedis即可
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

#不指定连接池
#spring:
#  redis:
#    cluster:
#      nodes:
#        192.168.10.120:7000,192.168.10.120:7001,192.168.10.111:7002,192.168.10.111:7003,192.168.10.114:7004,192.168.10.114:7005
#    pool:
#      max-redirects: 3  # 获取失败 最大重定向次数
#      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#      max-idle: 10      # 连接池中的最大空闲连接
#      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      min-idle:  5      # 连接池中的最小空闲连接
#      timeout: 6000     # 连接超时时长（毫秒）



#redis单机配置
#  redis:
#     host: 192.168.40.156
#     port: 6379
#      # 密码 没有则可以不填
#   password: 123456
#      # 如果使用的jedis 则将lettuce改成jedis即可
#   lettuce:
#        pool:
#          # 最大活跃链接数 默认8（使用负值表示没有限制）
#         max-active: 8
#          # 最大空闲连接数 默认8
#          	max-idle: 8
#          # 最小空闲连接数 默认0
#          	min-idle: 0
#          # 连接池最大阻塞等待时间（使用负值表示没有限制）
#         max-wait: -1


